### ISSUE TITLE
Publishing an updated fork to npm ?

### ISSUE THREAD

**Issue by mrseanryan** [pzavolinsky/ts-unused-exports#40]
hi Patricio

thanks for making this great tool!

I have made an updated fork, with all the 4 open PRs.

https://github.com/mrseanryan/ts-unused-exports-updated

would you mind if I published that to npm?
(package name `ts-unused-exports-updated`)

Currently am installing via yarn from git, which is awkward as it is fixed to a commit, rather than a published package.

In the readme, I made it clear that you are the original author.

Regards
Sean

**Comment by resynth1943** [comment]
I would say that you really shouldn't be splitting the community by making a new package, but this package seems to be unmaintained, which is reinforced by the extremely old version of TypeScript this project lists in it's dependencies.

I would say go for it, your fork is fine.

**Comment by pzavolinsky** [comment]
Hey @mrseanryan and @resynth1943 and everyone else watching this repo.

I've been pretty busy lately and was not able to pay as much attention to this repo as you all deserve. I'm sorry for the not being able to keep this up to date, but by the look of things I doubt I'll be able to maintain this anytime soon.

I'm OK with the fork, or I could make you a maintainer of this same repo if you feel you could put in the time.

Let me know what you think, lets make this a community decision.

Again, sorry for being unresponsive.

Cheers.

**Comment by resynth1943** [comment]
Yeah, that's a great idea. Thanks for being so honest about not being to maintain this any longer, too.

As I said, creating another package partially splits the community, so I think it should be *avoided*, and making an `updated` package really feels like bad practice. A shift of maintainers might restart this project again (the only reason I'm here is because of the terribly old TypeScript version this project uses).

Following this, if someone wants to follow this error, and send in a PR that updates that dependency, feel free. If not, I'm more than happy to.

Many thanks,
Will

**Comment by mrseanryan** [comment]
Hi @pzavolinsky and @resynth1943

I'd be happy to help to actively maintain the current project. 

I agree that forking to a new package on npm is not so good. 

Initially, we could first publish with the 4 open PRs (they seem to work well together) 
and then update the Typescript version. 

And then continue with other improvements :) 

Regards
Sean

**Comment by pzavolinsky** [comment]
Good man Sean, I've just sent you an invite to collab in this repo. Let's work out the details via email.

Cheers.

**Comment by mrseanryan** [comment]
Closing - will open a 'Roadmap' issue where we can discuss next steps.
